trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: CI
    displayName: 'CI - Build'

    jobs:
      - job: Build
        displayName: 'Build'

        steps:
          - checkout: self

          - task: Maven@4
            displayName: 'Build Maven'

            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package -DskipTests'

          - task: PublishPipelineArtifact@1
            displayName: 'Publicar JAR'

            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/target'
              artifact: 'jar-file'

  - stage: CD
    displayName: 'CD - Deploy'

    dependsOn: CI

    jobs:
      - job: Deploy
        displayName: 'Deploy'

        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Baixar artefato'

            inputs:
              artifact: 'jar-file'
              path: '$(Pipeline.Workspace)/artifact'

          - script: |
              set -e

              echo "Localizando JAR..."
              JAR_FILE=$(find "$(Pipeline.Workspace)/artifact" -name "*.jar" | head -n 1)

              echo "JAR encontrado:"
              echo "$JAR_FILE"

              echo "Enviando JAR para o App Service..."

              curl -v --fail -X PUT "https://$PUBLISH_URL/api/vfs/site/wwwroot/app.jar" \
                -u "$PUBLISH_USERNAME:$PUBLISH_PASSWORD" \
                -H "If-Match: *" \
                --data-binary @"$JAR_FILE"

              echo "Upload finalizado."
            displayName: 'Deploy direto do JAR'
            env:
              PUBLISH_URL: $(PUBLISH_URL)
              PUBLISH_USERNAME: $(PUBLISH_USERNAME)
              PUBLISH_PASSWORD: $(PUBLISH_PASSWORD)