trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azure-nutricode-service-connection'
  webAppName: 'appservice-nutricode'

stages:
  - stage: CI
    displayName: 'CI - Build'

    jobs:
      - job: Build
        displayName: 'Build'

        steps:
          - checkout: self

          - task: Maven@4
            displayName: 'Build Maven'

            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package -DskipTests'

          - task: PublishPipelineArtifact@1
            displayName: 'Publicar JAR'

            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/target'
              artifact: 'jar-file'

  - stage: CD
    displayName: 'CD - Deploy'

    dependsOn: CI

    jobs:
      - job: Deploy
        displayName: 'Deploy'

        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Baixar artefato'

            inputs:
              artifact: 'jar-file'
              path: '$(Pipeline.Workspace)/artifact'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure App Service'

            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/artifact/*.jar'