CREATE TABLE categoria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL
);

CREATE TABLE alimento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    categoria_id NUMBER,

    CONSTRAINT fk_categoria
    FOREIGN KEY (categoria_id)
    REFERENCES categoria(id)
);

INSERT INTO categoria (nome)
VALUES ('Fitness');

INSERT INTO categoria (nome)
VALUES ('Diabético');

INSERT INTO alimento (nome, descricao, categoria_id)
VALUES ('Frango', 'Alto teor de proteína', 1);

INSERT INTO alimento (nome, descricao, categoria_id)
VALUES ('Aveia', 'Baixo índice glicêmico', 2);