spring.application.name=projectNutricode
"
server.port=8081

# ORACLE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=560914
spring.datasource.password=fiap25
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA.
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=86400000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest