spring.application.name=projectNutricode
server.port=8080

# ORACLE
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=rm560914
spring.datasource.password=fiap25
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=86400000
